service: GVTeleBot
provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'ap-southeast-1'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  bot:
    timeout: 180
    memorySize: 2048
    image:
      name: img


          

